store/store/urls.py
from django.conf.urls import url
from django.contrib import admin
from mainapp.views import get_index, ajax_api, get_settings, get_buying, get_selling

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', get_index, name='home'),
    url(r'^api/$', ajax_api, name='api'),
    url(r'^settings/$', get_settings, name='settings'),
    url(r'^buying/$', get_buying, name='buying'),
    url(r'^selling/$', get_selling, name='selling'),

]

store/mainapp/models.py
from django.db import models
from django.utils import timezone


def averagenum(num):
    nsum = 0
    for i in range(len(num)):
        nsum += num[i]
    return nsum / len(num)


class Category(models.Model):
    name = models.CharField('Category', max_length=20, )

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category)
    name = models.CharField('Name', max_length=20, unique=True)
    price = models.FloatField('Price', default=0)
    cost = models.FloatField('Cost', default=0)
    cost_updated_at = models.DateTimeField(default=timezone.now)
    stock = models.IntegerField('Stock', default=0)
    stock_updated_at = models.DateTimeField(default=timezone.now)
    is_sell = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def update_cost(self):
        try:
            buys = self.buying_set.all()
        except Buying.DoesNotExist:
            return False
        if buys.count() > 0:
            all_cost_each_list = []

            for b in buys:
                # print(b)
                all_cost_each_list.append(b.cost / (b.qty_buy * b.qty_set))
            # print(all_cost_each_list)
            cost_each = round(averagenum(all_cost_each_list) * 100) / 100.00
            self.cost = cost_each
            self.cost_updated_at = timezone.now()
            self.save(update_fields=['cost', 'cost_updated_at'])
            return True

        return False

    def get_cost_avg(self):
        # print(self.buying_set.all())
        return self.cost

    def update_stock(self, qty):
        self.stock = self.stock + qty
        self.stock_updated_at = timezone.now()
        self.save(update_fields=['stock', 'stock_updated_at'])
        return True

    def get_stock(self):
        return self.stock


class Vendor(models.Model):
    name = models.CharField('Vender', max_length=10)

    def __str__(self):
        return self.name


class BuyingOrder(models.Model):
    date = models.DateField(default=timezone.now)
    vendor = models.ForeignKey(Vendor)

    def __str__(self):
        return str(self.date) + '-' + str(self.vendor)

    def get_total(self):
        from django.db.models import Sum
        sum = self.buying_set.aggregate(Sum('cost'))['cost__sum']
        if sum is None:
            return 0

        return sum


class Buying(models.Model):
    buying_order = models.ForeignKey(BuyingOrder)
    item = models.ForeignKey(Item)
    cost = models.FloatField('Price for Buy', default=1)
    # How many set for buy?
    qty_buy = models.IntegerField('QTY for Buy', default=1)
    # How many items per set?
    qty_set = models.IntegerField('QTY for Set', default=1)

    def get_qty_all(self):
        return self.qty_buy * self.qty_set

    def get_cost_each(self):
        return round((self.cost / (self.get_qty_all()) * 100)) / 100.00

    def get_subtotal(self):
        return self.cost * self.qty_buy


class Cashier(models.Model):
    date = models.DateTimeField(default=timezone.now)
    amount = models.IntegerField('Money', default=0)


class Selling(models.Model):
    date = models.DateField(default=timezone.now)
    time = models.TimeField(default=timezone.now)
    item = models.ForeignKey(Item)
    price = models.FloatField(default=1)
    cost = models.FloatField(default=1)
    qty = models.IntegerField(default=1)

store/mainapp/views.py
# mainapp/views.py
from django.shortcuts import render, redirect, reverse
from django.http import Http404, JsonResponse, HttpResponse, HttpResponseBadRequest
from .forms import *

from django.core.paginator import Paginator


# Create your views here.

def get_opening(date):
    try:
        return Cashier.objects.get(date__range=(date + ' 00:00:00', date + ' 23:59:59')).amount
    except Cashier.DoesNotExist:
        return None


# 取得URL的GET參數,移除某些reg
def get_url_GET(request, reg=r"&p=(\d+)"):
    import re
    return re.sub(reg, "", request.GET.urlencode())


def get_index(request):
    return redirect(reverse('selling') + '?t=cs')


def get_settings(request):
    # if request.method == 'GET':
    target = request.GET.get('t')
    # is_errs = request.GET.get('err')
    if target == 'category':
        obj_model = 'Category'
        obj_formset = 'Category_FormSet'

    elif target == 'vendor':
        obj_model = 'Vendor'
        obj_formset = 'Vendor_FormSet'

    elif target == 'items':
        cpk = request.GET.get('cpk')  # Category PK
        obj_model = 'Item'
        obj_formset = 'Item_Formset'
        try:
            obj_category = Category.objects.get(pk=cpk)
        except Category.DoesNotExist:
            raise Http404
    else:
        raise Http404

    if request.method == 'POST':
        formset = eval('{obj_formset}(request.POST)'.format(obj_formset=obj_formset))
        if target == 'items':
            formset = eval('{obj_formset}(request.POST,instance=obj_category)'.format(obj_formset=obj_formset))

            if cpk is not None:
                url_cpk = '&cpk=' + cpk
            else:
                url_cpk = ''

            if formset.is_valid():
                ii = formset.save(commit=False)
                for i in ii:
                    i.save()
                for obj in formset.deleted_objects:
                    obj.delete()
                return redirect(reverse('settings') + '?act=1&t=' + target + url_cpk)
            print(formset.total_error_count())

    formset = eval('{obj_formset}()'.format(obj_formset=obj_formset))
    if target == 'items':
        formset = eval('{obj_formset}(instance=obj_category)'.format(obj_formset=obj_formset))

    categorys = Category.objects.order_by('name').all()
    categorys_list = []
    for category in categorys:
        categorys_list.append((category.name, str(category.pk)))

    return render(request, 'settings.html', locals())


def get_buying(request):
    target = request.GET.get('t')
    if request.method == 'GET':
        if target == 'bl':
            cur_page = request.GET.get('p')
            if cur_page is None:
                cur_page = 1
            else:
                try:
                    cur_page = int(cur_page)
                except TypeError:
                    raise Http404

            bos = BuyingOrder.objects.order_by('-date', '-pk').all()

            pages = Paginator(bos, 20)
            try:
                bos = pages.page(cur_page)
            except:
                bos = pages.page(1)

            url_get = get_url_GET(request)

            return render(request, 'buying_list.html', locals())

        elif target == 'bn':
            formset = Buying_Formset()
            form = BuyingOrderForm()
            return render(request, 'buying_create.html', locals())

        elif target == 'od':
            opk = request.GET.get('opk')  # buyingorder pk
            cur_page = request.GET.get('p')

            if cur_page is None:
                cur_page = 1
            else:
                try:
                    cur_page = int(cur_page)
                except TypeError:
                    raise Http404

            try:
                objs = BuyingOrder.objects.get(pk=opk)
            except BuyingOrder.DoesNotExist:
                raise Http404

            items = Buying.objects.filter(buying_order=opk).order_by('pk').all()
            pages = Paginator(items, 20)
            try:
                items = pages.page(cur_page)
            except:
                items = pages.page(1)
            url_get = get_url_GET(request)

            return render(request, 'buying_detail.html', locals())

        else:
            raise Http404
    elif request.method == 'POST':
        if target == 'bn':
            form = BuyingOrderForm(request.POST)
            formset = Buying_Formset(request.POST)
            if form.is_valid() and formset.is_valid():
                bo = form.save(commit=True)
                for f in formset:
                    data = f.cleaned_data
                    items = Item.objects.get(pk=data['item'])
                    new_buy = Buying()
                    new_buy.buying_order = bo
                    new_buy.item = items
                    new_buy.cost = data['cost']
                    new_buy.qty_buy = data['qty_buy']
                    new_buy.qty_set = data['qty_set']
                    new_buy.save()
                    items.update_cost()
                    items.update_stock(data['qty_buy'] * data['qty_set'])
                return redirect(reverse('buying') + '?t=bl')
            return render(request, 'buying_create.html', locals())
    return render(request, 'buying.html', locals())


def get_selling(request):
    target = request.GET.get('t')
    if request.method == 'GET':
        if target == 'cs':
            open_amount = get_opening(timezone.now().strftime('%Y-%m-%d'))
            form = Selling_Date_Form()
            formset = Selling_Formset()
        elif target == 'sl':
            date = request.GET.get('d')
            cur_page = request.GET.get('p')
            if cur_page is None:
                cur_page = 1
            else:
                try:
                    cur_page = int(cur_page)
                except TypeError:
                    raise Http404
            if date is None:
                date = timezone.now().strftime('%Y-%m-%d')
            try:
                sells = Selling.objects.filter(date=date).order_by('-date', '-time', '-pk').all()
            except:
                pass
            pages = Paginator(sells, 20)
            try:
                sells = pages.page(cur_page)
            except:
                sells = pages.page(1)

            total = {'income': 0, 'profit': 0}
            for s in sells:
                total['income'] = total['income'] + (s.qty * s.price)
                total['profit'] = total['profit'] + ((s.price - s.cost) * s.qty)

            url_get = get_url_GET(request)
            # print(timezone.now())
            return render(request, 'selling_list.html', locals())
        elif target == 'op':
            form = Opening_Form()
            return render(request, 'opening_amount.html', locals())
        else:
            raise Http404
    elif request.method == 'POST':
        if target == 'cs':
            form = Selling_Date_Form(request.POST)
            formset = Selling_Formset(request.POST)
            print(request.POST)
            if form.is_valid() and formset.is_valid():
                for f in formset:
                    data = f.cleaned_data
                    items = Item.objects.get(pk=data['item'])
                    sell = Selling()
                    sell.date = form.cleaned_data['date']
                    sell.item = items
                    sell.price = items.price
                    sell.cost = items.cost
                    sell.qty = data['qty']
                    sell.save()
                    items.update_stock((data['qty'] * -1))
                return redirect(reverse('selling') + '?t=cs')
            else:
                print(formset.errors)
        elif target == 'op':
            form = Opening_Form(request.POST)
            if form.is_valid():
                data = form.save()
                script = '<script type="text/javascript">window.opener.parent.location.reload();window.close();</script>'
                return HttpResponse(script)
        else:
            raise Http404
    return render(request, 'selling_cashier.html', locals())


def ajax_api(request):
    content = {}
    target = request.GET.get('t')

    if target == 'selling':
        if request.method == 'GET':
            act = request.GET.get('act')
            if act == '1':  # get-items-price
                ipk = request.GET.get('ipk')
                content = {
                    'price': str(Item.objects.get(pk=ipk).price),
                    'cost': str(Item.objects.get(pk=ipk).cost),
                    'stock': str(Item.objects.get(pk=ipk).get_stock())
                }
                return JsonResponse(content)


    elif target == 'selling-change':
        spk = request.GET.get('spk')
        try:
            se = Selling.objects.get(pk=spk)
        except Selling.DoesNotExist:
            return HttpResponseBadRequest()

        if request.method == 'GET':
            form = Selling_Change_Form(initial={'item': se.item.pk}, instance=se)
            return render(request, 'ajax.html', locals())

        elif request.method == 'POST':
            orig_se = Selling.objects.get(pk=spk)
            content = {}
            form = Selling_Change_Form(request.POST, instance=se)

            if form.is_valid():
                data = form.save(commit=False)

                data.item = Item.objects.get(pk=request.POST['item'])
                if orig_se.item != data.item:
                    # 復原原品項庫存
                    orig_se.item.update_stock(orig_se.qty)
                    # 更新新品項庫存
                    se.item.update_stock(data.qty * -1)
                if orig_se.item == data.item:
                    # 同品項 庫存調整
                    se.item.update_stock((data.qty * -1) + orig_se.qty)
                form.save()
                content = {
                    'is_success': True,
                }
            else:
                print(form.errors)
            return JsonResponse(content)

        elif request.method == 'DELETE':
            # 調整庫存數量

store/mainapp/templates/ajax.html
{# mainapp/templates/ajax.html #}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% if target == 'selling-change' or target == 'buying-change' or target == 'buying-order-add' %}
    <form id="id-change-form">
        <div class="modal-body">
            <div class="form-group">
                {% csrf_token %}
                {% crispy form %}
            </div>
        </div>
        <div class="modal-footer">
            <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary" id="btn-change-form"
                        data-dismiss="modal">Save
                </button>
                <button type="button" class="btn btn-sm btn-outline-secondary" data-dismiss="modal">Cancel
                </button>
            </div>
        </div>
    </form>
{% endif %}

store/mainapp/templates/buying_create.html
{# templates/index.html #}
{% extends "default/main.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load common_tags %}

{% block title %}Buying{% endblock title %}

{% block main %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2">
        <h1 class="h2"><i class="fas fa-shopping-bag"></i> Buying</h1>
    </div>

    <div style="width: 90%">
        <form method="post" class="form-group">
            {% csrf_token %}

            <div id="order_form" class="form-group mb-2 ml-2">
                {% crispy form %}
            </div>

            <div id="buying_form" class="form-group border p-4">
                <div class="row m-0 font-weight-bold align-middle text-md-center">
                    <label class="col-1"></label>
                    <label class="col-4">Item</label>
                    <label class="col-2">Cost</label>
                    <label class="col-1">QTY/Buy</label>
                    <label class="col-1">QTY/Set</label>
                    <label class="col-1">Cost/Each</label>
                    <label class="col-1">QTY/Stock</label>
                    <label class="col-1">Subtotal</label>
                    {#        <label class="col-2"></label>#}
                </div>

                {{ formset.management_form }}
                {% for form in formset %}
                    <div class="item">
                        {% crispy form formset.helper %}
                    </div>
                {% endfor %}
                <div class="row border-top p-3 m-2">
                    <div class="col-10">
                        <button href="#" class="item-add btn btn-sm btn-outline-secondary" accesskey="a">
                            <i class="fas fa-plus"></i> Add
                        </button>
                    </div>
                    <div class="col-2">
                        <label class="font-weight-bold">Total</label>
                        <span id="id_total" style="float: right">0.00</span>
                    </div>
                </div>

            </div>
            <div class="text-md-right">
                <div class="btn-group">
                    <button type="submit" class="btn btn-sm btn-outline-secondary">
                        <i class="fas fa-edit"></i> Update
                    </button>
                    <button type="button" class="btn btn-sm btn-outline-secondary" onclick="window.location.href='{% url 'buying' %}?t=bl';">
                        <i class="fas fa-times"></i> Cancel
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock main %}

{% block js %}

    <script type="text/javascript">
        (function ($) {
            $('.item-add').click(function (e) {
                e.preventDefault();

                var lastElement = $('.item:last');
                var totalForms = $('#id_form-TOTAL_FORMS');
                var total = parseInt(totalForms.val());
                console.log(total);
                var newElement = lastElement.clone(true);

                newElement.find(':input').each(
                    function () {
                        var name = $(this).attr('name').replace(
                            '-' + (total - 1) + '-',
                            '-' + total + '-'
                        );
                        console.log(name);
                        $(this).attr({'name': name}).val('').removeAttr('checked');
                    }
                );
                newElement.find('*').each(
                    function () {
                        var id = $(this).attr('id');
                        if (id) {
                            $(this).attr('id', id.replace(
                                '-' + (total - 1) + '-',
                                '-' + total + '-'
                            ));
                        }
                    }
                );
                totalForms.val(total + 1);
                newElement.insertAfter(lastElement);
                update_no();
            });
            $('.ipt_field').change(function (e) {

                update_field($(this));
                update_qty_set($(this));
                // alert($(this).attr('id'));
            });
            update_no();

            $('#id_date').datepicker({
                dateFormat: 'yy-mm-dd',
            });
            $('.btn-date').click(function () {
                $('#id_date').focus();
            })

        })(jQuery);
        function update_qty_set(obj) {
            var id = parseInt(obj.attr('id').split('-')[1]);
            var qty_set = $('#id_form-' + id + '-qty_set');
            if (qty_set.val() === null || qty_set.val() <= 0){
                qty_set.val(1)
            }
        }

        function update_field(obj) {

            var id = parseInt(obj.attr('id').split('-')[1]);
            var cost = $('#id_form-' + id + '-cost').val();
            var qty_buy = $('#id_form-' + id + '-qty_buy').val();
            var qty_set = $('#id_form-' + id + '-qty_set').val();
            var cost_each = $('#id_form-' + id + '-cost_of_each');
            var total_buy = $('#id_form-' + id + '-total_of_buy');
            var subtotal = $('#id_form-' + id + '-subtotal');

            if ((qty_buy > 0) && (qty_set > 0)) {
                total_buy.val(qty_buy * qty_set);
            }
            if (cost > 0 && qty_set > 0) {
                cost_each.val(Math.round((cost / qty_set) * 100) / 100);
            }
            if (cost > 0 && qty_buy > 0) {
                subtotal.val(Math.round((cost * qty_buy) * 100) / 100);
            }
            var total_cost = 0;
            var totalForms = parseInt($('#id_form-TOTAL_FORMS').val());
            for (var x = 0; x <= totalForms; x++) {
                var subtotal = $('#id_form-' + x + '-subtotal').val();
                if (subtotal > 0) {
                    total_cost += parseInt(subtotal);
                }
            }
            $('#id_total').text(total_cost);

        }


        function update_no() {
            $('.ipt_no').each(
                function () {
                    $(this).val(parseInt($(this).attr('id').split('-')[1]) + 1);
                }
            );
        }
    </script>

{% endblock js %}

store/mainapp/templates/index.html
{# templates/index.html #}
{% extends "default/main.html" %}
{% load staticfiles %}

{% block title %}Index{% endblock title %}

{% block main %}
<i class="far fa-money-bill-alt"></i>
{% endblock main %}

store/mainapp/templates/opening_amount.html
{#  templates/opening_amount.html #}
{% extends 'default/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load common_tags %}

{% block title %}Opening Store{% endblock title %}

{% block content %}
    <div class="container-fluid">
        <div class="m-3">
            <form method="post" class="">
                <div class="form-group border p-3">
                    {% crispy form %}
                </div>
                <div class="form-row">
                    <div class="col-9"></div>
                    <div class="btn-group col-1">

                        <button class="btn btn-sm btn-outline-secondary" type="submit">
                            <i class="fas fa-edit"></i> Save
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

{% block js %}
<script type="text/javascript">

</script>
{% endblock js %}

store/mainapp/templates/selling_list.html
{# templates/index.html #}
{% extends "default/main.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load common_tags %}
{% load humanize %}

{% block title %}Selling{% endblock title %}

{% block main %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2">
        <h1 class="h2"><i class="fas fa-dollar-sign"></i> Selling</h1>
    </div>
    <div class="pb-5 mt-1 col-11">
        <div class="mb-2 pt-0 row">
            <div class="col-3">
                <div class="input-group" style="width: 75%">
                    <label for="id_date" class="h6 mr-2 align-middle">Date: </label>
                    <input type="text" name="date" class="form-control-sm dateinput form-control"
                           style="text-align: center;" value="{{ date }}" id="id_date">
                    <span class="input-group-append">
                    <button class="btn btn-sm btn-date" type="button">
                    <i class="far fa-calendar-alt"></i></button>
                </span>
                </div>
            </div>
            <div class="col-5">&nbsp;</div>
            <div class="col-4 row text-right border" style="border-style: dashed!important;">
                <div class="col-6 text-left">
                    <label class="h6">Total Income:</label>
                    <span class="h6">$<span style="float: right">{{ total.income|floatformat:2|intcomma }}</span></span>
                </div>
                <div class="col-6 text-left">
                    <label class="h6">Total Profit:</label>
                    <span class="h6">$<span style="float: right">{{ total.profit|floatformat:2|intcomma }}</span></span>
                </div>

            </div>
        </div>

        <table class="table table-sm table-bordered table-light table-striped table-hover mb-3">
            <thead>
            <tr class="text-md-center align-middle">
                <th width="50">#</th>
                <th width="130">Date</th>
                <th width="100">Time</th>
                <th width="12%">Category</th>
                <th>Items</th>
                <th width="80">QTY</th>
                <th width="120">Price</th>
                <th width="120">Subtotal</th>
                <th width="120">Cost/Each</th>
                <th width="120">Profit/Each</th>
                <th width="60"></th>
            </tr>
            </thead>
            <tbody>
            {% for se in sells %}
                <tr class="text-md-center align-middle">
                    <th>{{ forloop.counter }}</th>
                    <td>{{ se.date|date:"Y-m-d" }}</td>
                    <td>{{ se.time|time:"H:i" }}</td>
                    <td>{{ se.item.category }}</td>
                    <td>{{ se.item.name }}</td>
                    <td>{{ se.qty }}</td>
                    <td class="text-md-left">$
                        <div style="float: right">{{ se.price|floatformat:2|intcomma }}</div>
                    </td>
                    <td class="text-md-left">$
                        <div style="float: right">{{ se.qty|get_times:se.price|floatformat:2|intcomma }}</div>
                    </td>
                    <td class="text-md-left">$
                        <div style="float: right">{{ se.cost|floatformat:2|intcomma }}</div>
                    </td>
                    <td class="text-md-left">$
                        <div style="float: right">{{ se|get_sell_profit|floatformat:2|intcomma }}</div>
                    </td>
                    <td>
                        <a href="#" class="text-secondary btn-edit" data-key="{{ se.pk }}" data-toggle="modal"
                           data-target="#modal-change"><i class="fas fa-pen-square"></i></a>&nbsp;
                        <a href="#" class="text-secondary btn-del" data-key="{{ se.pk }}"><i
                                class="fas fa-minus-square"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <nav aria-label="Page navigation" class="mb-5">
            <ul class="mt-2 pagination justify-content-end">
                {# 上一页，这里需要用到has_previous方法判断是否有上一页 #}
                <li class="page-item">
                    <a href="{% url 'selling' %}?{{ url_get }}&p=1" class="page-link text-secondary"
                       aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>

                {# 遍历所有页码 #}
                {% for page in pages.page_range %}
                    <li class="page-item"><a href="{% url 'selling' %}?{{ url_get }}&p={{ page }}"
                                             class="page-link text-secondary">{{ page }}</a></li>
                {% endfor %}

                <li class="page-item">
                    <a href="{% url 'selling' %}?{{ url_get }}&p={{ pages.num_pages }}" aria-label="Next"
                       class="page-link text-secondary">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>

    <div class="modal fade" id="modal-change" tabindex="-1">
        <div class="modal-dialog" style="max-width: 450px">
            <div class="modal-content">
                <div class="modal-header">
                    <h6>Change Selling</h6>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div id="id-modal-change-body">
                    ...
                </div>
            </div>
        </div>
    </div>



{% endblock main %}

{% block js %}
    <script type="text/javascript">
        (function ($) {

            /*** date picker ***/
            var id_date = $('#id_date');

            id_date.datepicker({
                dateFormat: 'yy-mm-dd',
            });

            id_date.change(function () {
                location = '{% url 'selling' %}?t=sl&d=' + $(this).val();
            });

            $('.btn-date').click(function () {
                id_date.focus();
            });
            /*** ############ ***/

            $('.btn-edit').click(function () {
                var url = '{% url 'api' %}?t=selling-change&spk=' + $(this).data('key');
                $.ajax({
                    method: "GET",
                    url: url,
                    success: function (ret) {
                        $('#id-modal-change-body').html(ret);
                        // 物品更改時重新查詢單價與成本
                        $('#id_item').change(function () {
                            var ipk = $(this).val();
                            $.ajax({
                                method: "GET",
                                url: '{% url 'api' %}?t=selling&act=1&ipk=' + ipk,
                                cache: false,
                                success: function (ret) {
                                    console.log(ret);
                                    $('#id_price').val(ret.price);
                                    $('#id_cost').val(ret.cost);
                                }
                            });
                        });
                        $('#btn-change-form').click(function () {
                            $('#id-change-form').ajaxSubmit({
                                method: "POST",
                                url: url,
                                success: function (ret) {
                                    console.log(ret);
                                    if (ret.is_success) {
                                        location.reload();
                                    }
                                }
                            })
                        });
                    }
                });
            });

            $('.btn-del').click(function () {
                var url = '{% url 'api' %}?t=selling-change&spk=' + $(this).data('key');
                if (confirm("This action CANNOT be restored,\n Are you sure??") === true) {
                    $.ajax({
                        method: 'DELETE',
                        url: url,
                        beforeSend: function (xhr) {
                            xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
                        },
                        success: function (ret) {
                            console.log(ret);
                            if (ret.is_success) {
                                window.location.href = ret.url;
                            }
                        }
                    });

                }
            });
        })(jQuery);

    </script>

{% endblock js %}